# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_volume', models.FloatField()),
                ('duration', models.TimeField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='crop',
            name='optimal_water_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='water_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='trigger',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Crop'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
