# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170317_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='time_stamp',
            new_name='irrigation_time',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='crop',
        ),
    ]
