# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170319_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='duration',
            field=models.CharField(max_length=250),
        ),
    ]
