# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170319_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=40),
            preserve_default=False,
        ),
    ]
